# Site settings
title: Himangshu Hazarika's CV
description: Himangshu Hazarika's CV
favicon: /resume/assets/img/avatar.JPG
baseurl: http://himangshu.io/resume/
url: http://himangshu.io/resume/
rss_url: /resume/pages/atom.xml

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Himangshu Hazarika
  title: Software Developer
  address: Bangalore, India
  email: hjhazarika@gmail.com
  link: http://himangshu.io
  stackoverflow: himangshuj
  github: himangshuj
  linkedin: himangshu
  twitter: himangshuj
  gavatar: /resume/assets/img/avatar.JPG
  workHistory:
    - work1:
      company: Youngmonk Technologies Pvt. Ltd.
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: Agfa HealthCare
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: Citigroup Services and Technology (China) Limited
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: Northeastern University
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Japanese
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: Java
      percentage: 100%
    - skill2:
      name: Clojure
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 90%
    - skill4:
      name: AngularJS
      percentage: 90%
    - skill5:
      name: Postgres
      percentage: 90%
    - skill6:
      name: Microservice
      percentage: 90%
    - skill7:
      name: SCSS/LESS
      percentage: 60%
    - skill8:
      name: Spring
      percentage: 90%
    - skill9:
      name: Android
      percentage: 70%
    - skill10:
      name: Mongodb
      percentage: 80%
    - skill11:
      name: Erlang
      percentage: 60%
    - skill12:
      name: AWS
      percentage: 70%